### ISSUE TITLE
current version does not compile

### ISSUE THREAD

**Issue by bigbadbrad** [uilibrary/matx-react#11]
It's throwing a library error - see attached.
<img width="1244" alt="Screen Shot 2021-04-16 at 1 40 02 PM" src="https://user-images.githubusercontent.com/1226677/115083222-e7cd5a80-9ebb-11eb-8892-e8af08445b39.png">

**Comment by reginz** [comment]
yeah, I'm also getting the same error. I tried `npm rebuild node-sass`, deleted and installed node modules but didn't work.

**Comment by reginz** [comment]
okay so in case you still couldn't compile it I found a way. here is the link:  https://github.com/grpc/grpc-node/issues/1183#issuecomment-596956959

**Comment by nineunderground** [comment]
I've fixed myself the free project with following changes...

1. Update the package.json and replace all dependencies with following

```
    "@date-io/date-fns": "^1.3.6",
    "@material-ui/core": "^4.3.1",
    "@material-ui/icons": "^4.2.1",
    "@material-ui/lab": "^4.0.0-alpha.22",
    "@material-ui/pickers": "^3.2.2",
    "autosuggest-highlight": "^3.1.1",
    "axios": "^0.21.1",
    "babel-polyfill": "^6.26.0",
    "clsx": "^1.0.4",
    "css-vars-ponyfill": "^2.1.2",
    "date-fns": "^2.0.0-alpha.34",
    "downshift": "^3.2.10",
    "echarts": "^4.2.1",
    "echarts-for-react": "^2.0.15-beta.0",
    "firebase": "^8.6.3",
    "history": "^4.10.0",
    "lodash": "^4.17.15",
    "material-ui": "^1.0.0-beta.47",
    "moment": "^2.24.0",
    "node-sass": "^6.0.0",
    "notistack": "^1.0.9",
    "qwest": "^4.5.0",
    "react": "^17.0.2",
    "react-app-polyfill": "^1.0.2",
    "react-autosuggest": "^9.4.3",
    "react-beautiful-dnd": "^13.1.0",
    "react-big-calendar": "^0.33.4",
    "react-dom": "^17.0.2",
    "react-google-maps": "^9.4.5",
    "react-helmet": "^6.1.0",
    "react-highlight": "^0.14.0",
    "react-html-parser": "^2.0.2",
    "react-infinite-scroller": "^1.2.4",
    "react-loadable": "^5.5.0",
    "react-material-ui-form-validator": "^2.1.4",
    "react-perfect-scrollbar": "^1.5.8",
    "react-quill": "^1.3.5",
    "react-redux": "^7.2.4",
    "react-router-config": "^5.1.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.3",
    "react-select": "^4.3.1",
    "react-vis": "^1.11.7",
    "recharts": "^2.0.9",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0",
    "shortid": "^2.2.14",
    "swiper": "^4.5.0",
    "victory": "^32.3.3"
```

2. Move the assets folder from "/public" and all its content under "/src" path.

3. Replace all URLs that are loading image in style files.
So replace and use "./../../assets/images", instead of "/assets/images"

4. Finally run:
npm install --legacy-peer-deps
npm start

**Comment by mh-rafi** [comment]
Updated the template, hope this issue is fixed :)

**Comment by gsaltintas** [comment]
Hello, thank you for the template. For your information, the template code on your website still contains the bug.

**Comment by mh-rafi** [comment]
@gsaltintas updated on website. 
https://ui-lib.com/downloads/matx-react-dashboard/

Thanks
