### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by jwhitehorn** [uilibrary/matx-react#18]
What license is this released under?

Prior to commit [68181c50a782e458228c2f464e9212c6efc57677](https://github.com/uilibrary/matx-react/commit/68181c50a782e458228c2f464e9212c6efc57677), this project was released under an MIT license. That commit removed the licensing information.

Without a license at all this project isn't a good fit for a public Github repo, nor is it something anyone can easily use in their own projects.

**Comment by mh-rafi** [comment]
File is restored.
Thanks for the heads up :)
