### ISSUE TITLE
Cannot install dependencies

### ISSUE THREAD

**Issue by jbrainz** [uilibrary/matx-react#19]
![Screenshot from 2021-10-06 16-22-03](https://user-images.githubusercontent.com/24702087/136234930-d3d0806d-243d-4725-8058-7de371d1e63e.png)

when i try to `npm install` on the root dir. i get the error.

**Comment by mh-rafi** [comment]
Which OS & node version you are using?

**Comment by jbrainz** [comment]
i am on arch linux. i managed to fix this by downgrading my node to v12
 and updating my npm

**Comment by jbrainz** [comment]
i'm closing this issue now.
