### ISSUE TITLE
suggestions [reactivesearch/react-admin]

### ISSUE THREAD

**Issue by ghost** [uilibrary/matx-react#2]
Hi,

Hope you are all well !

It would be nice to add https://github.com/appbaseio/reactivesearch for faceted search interface, and to integrate a ui based on https://github.com/marmelab/react-admin

Is there a way to setup the menu and the layout of the admin panel from yaml configuration file ?

Cheers,
X

**Comment by mh-rafi** [comment]
Sorry for the late reply. I've plan to add reactivesearch. 

Layout options are coming from redux store. I have not done any research on how to get initial data from yaml file. You can give a try and let me know :)
