### ISSUE TITLE
Navigations Based on User Role

### ISSUE THREAD

**Issue by deddla** [uilibrary/matx-react#23]
Hi , Side Nav Navigations are not working based on User Role. Looks like this was broken in matx-react 3.0.0 which was worked fine in matx-react 1.0.0
Can some one help me to fix this in matx-react 3.0.0

thanks in advance

**Comment by mh-rafi** [comment]
Hi, role based authentication is fixed. Thanks

**Comment by deddla** [comment]
> Hi, role based authentication is fixed. Thanks

Thanks alot
