### ISSUE TITLE
Navigation bar doesn't hide menui tems on different roles

### ISSUE THREAD

**Issue by tomeszmh** [uilibrary/matx-react#27]
I logged in with different users, and different roles and I am not able to reach forbidden paths, but menu items still visible for all users. It seems getNavigationByUser() is not fired.
I think it's provided by free tier, am I right?
Can you please provide a solution?

**Comment by mh-rafi** [comment]
This is fixed in pro version. User role protection is not available in free version.

**Comment by klim42** [comment]
Hello, i buy a pro version but role protection dont work

**Comment by naime-hossain** [comment]
Please check the latest version. thanks
