### ISSUE TITLE
Material Table Enter key problem

### ISSUE THREAD

**Issue by gtavoalva** [uilibrary/matx-react#31]
If the table has Combobox items defined for one or more columns and has a validation for it, this validation is not working when "enter" key is pressed, saving the item anyway.
For example, for this definition:

```
<MaterialTable
          columns={[
            {
              title: 'Sucursal', field: 'sucursal', lookup: sucursalO, editPlaceholder: 'Sucursal',
              validate: rowData => rowData.sucursal !== undefined
            },
            {
              title: 'Nombre', field: 'nombre',
              validate: (rowData) => (!!rowData.nombre)
            },
```
...

if we fill the "nombre" field but "sucursal" is not selected, the "enter" key is pressed, and the validation for "sucursal" doesn't work.

**Comment by naime-hossain** [comment]
@nabedkhan
