### ISSUE TITLE
Function components

### ISSUE THREAD

**Issue by av8ta** [uilibrary/matx-react#4]
First of all, thanks for the pretty application! I liked it so much I bought the pro version. Just wondering if you would consider changing from class components to functional ones to make the usage of react hooks possible?

**Comment by mh-rafi** [comment]
Hi, we are working on that for pro version. Can you send your email address(which you used to purchase pro version) to support@ui-lib.com, I'll add you to pro version repository. so get the updates.

**Comment by av8ta** [comment]
Hi @mh-rafi I sent you an email. Should I be able to pull from https://github.com/mh-rafi/matx-react-pro.git/ now? When I try I get ```fatal: repository 'https://github.com/mh-rafi/matx-react-pro.git/' not found```

**Comment by lakshmigandh** [comment]
Hi @mh-rafi @shahalihridoy Does this have support for RTL ?
Including Right Sidemenu

**Comment by mh-rafi** [comment]
@lakshmigandh RTL is not supported right now. we're working on it.

**Comment by gliitterpuke** [comment]
Hey @mh-rafi @av8ta ! I sent an email in asking for repo access :) I previously purchased the template and it's the same email as the one I sent in.

**Comment by lakshmigandh** [comment]
@mh-rafi If possible, could you please help on making the side bar right ?
