### ISSUE TITLE
Dynamic Route not working 

### ISSUE THREAD

**Issue by JE-Zenarosa** [uilibrary/matx-react#40]
import AuthGuard from 'app/auth/AuthGuard';
import chartsRoute from 'app/views/charts/ChartsRoute';
import dashboardRoutes from 'app/views/dashboard/DashboardRoutes';
import materialRoutes from 'app/views/material-kit/MaterialRoutes';
import NotFound from 'app/views/sessions/NotFound';
import sessionRoutes from 'app/views/sessions/SessionRoutes';
import { Navigate } from 'react-router-dom';
import MatxLayout from './components/MatxLayout/MatxLayout';
import  loginRoutes from 'app/views/modular/Login/LoginRoutes';
import  usersRoute from 'app/views/modular/UserManagement/route';

var arrayModules = [];

let data = require.context("app/views/modular", true, /\index.js$/, 'lazy');

Promise.all(
  data.keys().map((item)=>{
    const cleanModule = item.substring(item.indexOf('./') + 1);
  
    return import(`app/views/modular${cleanModule.replace('/index.js','')}`).then(component=>{            
      
      return component.default;
    })    
  })  
).then(res=>{

  res.map((item)=>{
    
    arrayModules.push(...item)
  })

  

});

const routes = [

  ...loginRoutes,
  {
      
    // children: [...dashboardRoutes, ...chartsRoute, ...materialRoutes,...usersRoute],
    children: arrayModules,
    element: (
      <AuthGuard>
        <MatxLayout />    
      </AuthGuard>
    )
  },
  { path: '/', element:   <AuthGuard><Navigate to="/users" /> </AuthGuard>},
  { path: '*', element:<NotFound /> },
  
  
];

export default routes;

**Comment by naime-hossain** [comment]
@nabedkhan

**Comment by nabedkhan** [comment]
```js
return import(`app/views/modular/${cleanModule.replace('/index.js','')}`).then(component=>{            
  
  return component.default;
}) 
```

Try it now. You didn't put a slash in your code (`app/views/modular` ) after modular. I think that's why your code doesn't work. @Standin-Alone
