### ISSUE TITLE
npm bugs matx-react

### ISSUE THREAD

**Issue by amin1562** [uilibrary/matx-react#41]
[npm-debug.log](https://github.com/uilibrary/matx-react/files/9111009/npm-debug.log)

> matx-react@3.0.0 start /root/bot
> react-scripts start

sh: 1: react-scripts: not found

npm ERR! Linux 4.15.0-189-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! matx-react@3.0.0 start: `react-scripts start`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the matx-react@3.0.0 start script 'react-scripts start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the matx-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs matx-react
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls matx-react
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/bot/npm-debug.log

**Comment by naime-hossain** [comment]
@nabedkhan  check this issue

**Comment by nabedkhan** [comment]
In your code react-scripts are missing that's why doesn't work. Please remove the node_modules folder and run again ``npm install or yarn install`` @amin1562
