### ISSUE TITLE
npm start errors with ERR_OSSL_EVP_UNSUPPORTED

### ISSUE THREAD

**Issue by jyswee** [uilibrary/matx-react#46]
Hello,
I am trying to run on a macbook. 
npm install
and then nm start - but returns this..

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/--/matx-react/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/--/matx-react/node_modules/webpack/lib/NormalModule.js:417:16)
    at /--/matx-react/node_modules/webpack/lib/NormalModule.js:452:10
    at /--/matx-react/node_modules/webpack/lib/NormalModule.js:323:13
    at /--/matx-react/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /--/matx-react/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/--/matx-react/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /--/matx-react/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Can you shed any light onto why?
thanks
Joe

**Comment by Kae-Tempest** [comment]
same on win 11 22h2

**Comment by keelz** [comment]
same here

**Comment by oottoohh** [comment]
same here

**Comment by nabedkhan** [comment]
We update the dependencies & try again @oottoohh @keelz @Kae-Tempest
