### ISSUE TITLE
Error with Authentication Flow

### ISSUE THREAD

**Issue by M0W93** [uilibrary/matx-react#5]
Hello,
first of all thank you for you're great work. I just love the Dashboard and currently I'm checking whether i can use it productively. 
At the moment im trying to connect the dashboard to my small JWT Authentication Server (Node + Express). I just changed the loginWithEmailAndPassword() & loginWithToken() methods and getting the following error. The Servers responses in the console looks pretty fine.
The Error comes every time i try to login. 
Do you have any idea what is going on?

Greetings

loginWithEmailAndPassword():
https://pastebin.com/jCz4uryt

loginWithToken():
https://pastebin.com/RpcbwzNW

![image](https://user-images.githubusercontent.com/5788416/76849778-5ae24880-6846-11ea-9457-2a8b6f35895e.png)

**Comment by mh-rafi** [comment]
Authentication is updated and fixed.
